using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.Persistence.Configurations;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("users");

        // Internal primary key
        builder.HasKey(u => u.Id);
        builder.Property(u => u.Id).ValueGeneratedOnAdd();

        // Public identifier, generated by the database on insert
        builder.Property(u => u.UserUuid).HasDefaultValueSql("gen_random_uuid()").ValueGeneratedOnAdd().IsRequired();
        builder.HasIndex(u => u.UserUuid).IsUnique();

        builder.Property(u => u.Name).HasMaxLength(100);

        // Lowercase the email before saving (in your service), because
        // PostgreSQL unique indexes are case-sensitive
        builder.Property(u => u.Email).HasMaxLength(150).IsRequired();
        builder.HasIndex(u => u.Email).IsUnique();

        builder.Property(u => u.PasswordHash).HasMaxLength(500).IsRequired();

        builder.Property(u => u.Status).HasConversion<int>().IsRequired();

        builder.Property(u => u.IsVerified).IsRequired();

        // Nullable: null = no role assigned yet
        builder.Property(u => u.Role).HasConversion<int>();

        builder.Property(u => u.CreatedAtUtc).IsRequired();
        builder.Property(u => u.UpdatedAtUtc).IsRequired();

        // Computed properties are not stored
        builder.Ignore(u => u.CanAccessSystem);
        builder.Ignore(u => u.HasFullAccess);
    }
}